# Generated by Django 6.0.6 on 2026-06-22 22:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_remove_produto_estoque_produto_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('comida_rapida', 'Comida rápida'), ('bebida', 'Bebida'), ('doces_salgados', 'Doces / Salgados'), ('equipamentos', 'Equipamentos'), ('jogos', 'Jogos'), ('servicos', 'Serviços de lan house')], default='servicos', max_length=50, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Barras'),
        ),
        migrations.AddField(
            model_name='produto',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Cadastro'),
            preserve_default=False,
        ),
    ]
